echom getcwd()
echom "Hello, world!"
echom "Hello, world!"
echom "Hello, world!"
echom "Hello, world!"
echom "Hello, world!"
echom "Hello, world!"
echom "Hello, world!"
echom "Hello, world!"
echom "Hello, world!"
